import getSlots from '../utils/wenbin';
let slots = [
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "Lecture",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 1,
        "merged_lectures": false,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1,
        "start": "2018-01-29T08:00:00+08:00",
        "end": "2018-01-29T09:30:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "Lecture",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 1,
        "merged_lectures": false,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 2,
        "start": "2018-01-29T09:30:00+08:00",
        "end": "2018-01-29T11:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "Lecture",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 1,
        "merged_lectures": false,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 3,
        "start": "2018-01-29T11:00:00+08:00",
        "end": "2018-01-29T12:30:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "Lecture",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 1,
        "merged_lectures": false,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 4,
        "start": "2018-01-29T12:30:00+08:00",
        "end": "2018-01-29T14:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "Lecture",
        "student_count": 38,
        "hrs": 1,
        "session_number": 2,
        "merged_lectures": false,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1,
        "start": "2018-01-29T14:00:00+08:00",
        "end": "2018-01-29T15:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "Lecture",
        "student_count": 38,
        "hrs": 1,
        "session_number": 2,
        "merged_lectures": false,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 2,
        "start": "2018-01-29T15:00:00+08:00",
        "end": "2018-01-29T16:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "Lecture",
        "student_count": 37,
        "hrs": 1,
        "session_number": 2,
        "merged_lectures": false,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 3,
        "start": "2018-01-29T16:00:00+08:00",
        "end": "2018-01-29T17:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "Lecture",
        "student_count": 37,
        "hrs": 1,
        "session_number": 2,
        "merged_lectures": false,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 4,
        "start": "2018-01-29T17:00:00+08:00",
        "end": "2018-01-29T18:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1,
        "start": "2018-01-30T08:00:00+08:00",
        "end": "2018-01-30T09:30:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 2,
        "start": "2018-01-30T09:30:00+08:00",
        "end": "2018-01-30T11:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 3,
        "start": "2018-01-30T11:00:00+08:00",
        "end": "2018-01-30T12:30:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 4,
        "start": "2018-01-30T12:30:00+08:00",
        "end": "2018-01-30T14:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "CBL",
        "student_count": 38,
        "hrs": 2,
        "session_number": 2,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1,
        "start": "2018-01-30T14:00:00+08:00",
        "end": "2018-01-30T16:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "CBL",
        "student_count": 38,
        "hrs": 2,
        "session_number": 2,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 2,
        "start": "2018-01-30T16:00:00+08:00",
        "end": "2018-01-30T18:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "CBL",
        "student_count": 37,
        "hrs": 2,
        "session_number": 2,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 3,
        "start": "2018-01-31T08:00:00+08:00",
        "end": "2018-01-31T10:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "10.009",
        "subj_name": "The Digital World",
        "type": "CBL",
        "student_count": 37,
        "hrs": 2,
        "session_number": 2,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 4,
        "start": "2018-01-31T10:00:00+08:00",
        "end": "2018-01-31T12:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "Lecture",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 1,
        "merged_lectures": false,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1,
        "start": "2018-01-31T12:00:00+08:00",
        "end": "2018-01-31T13:30:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "Lecture",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 1,
        "merged_lectures": false,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 2,
        "start": "2018-01-31T13:30:00+08:00",
        "end": "2018-01-31T15:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "Lecture",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 1,
        "merged_lectures": false,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 3,
        "start": "2018-01-31T15:00:00+08:00",
        "end": "2018-01-31T16:30:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "Lecture",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 1,
        "merged_lectures": false,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 4,
        "start": "2018-01-31T16:30:00+08:00",
        "end": "2018-01-31T18:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1,
        "start": "2018-02-01T08:00:00+08:00",
        "end": "2018-02-01T09:30:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 2,
        "start": "2018-02-01T09:30:00+08:00",
        "end": "2018-02-01T11:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 3,
        "start": "2018-02-01T11:00:00+08:00",
        "end": "2018-02-01T12:30:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 4,
        "start": "2018-02-01T12:30:00+08:00",
        "end": "2018-02-01T14:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 2,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1,
        "start": "2018-02-01T14:00:00+08:00",
        "end": "2018-02-01T15:30:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 2,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 2,
        "start": "2018-02-01T15:30:00+08:00",
        "end": "2018-02-01T17:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 2,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 3,
        "start": "2018-02-01T17:00:00+08:00",
        "end": "2018-02-02T08:30:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 2,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 4,
        "start": "2018-02-02T08:30:00+08:00",
        "end": "2018-02-02T10:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 3,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1,
        "start": "2018-02-02T10:00:00+08:00",
        "end": "2018-02-02T11:30:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 3,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 2,
        "start": "2018-02-02T11:30:00+08:00",
        "end": "2018-02-02T13:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 3,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 3,
        "start": "2018-02-02T13:00:00+08:00",
        "end": "2018-02-02T14:30:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 3,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 4,
        "start": "2018-02-02T14:30:00+08:00",
        "end": "2018-02-02T16:00:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 4,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1,
        "start": "2018-02-02T16:00:00+08:00",
        "end": "2018-02-02T17:30:00+08:00",
        "location": "cc14"
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 4,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 2
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 4,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 3
    },
    {
        "subj_code": "50.002",
        "subj_name": "Introduction to Computation Structures",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 4,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 4
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "Lecture",
        "student_count": 150,
        "hrs": 1.5,
        "session_number": 1,
        "merged_lectures": true,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "Lecture",
        "student_count": 150,
        "hrs": 1.5,
        "session_number": 2,
        "merged_lectures": true,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "Lecture",
        "student_count": 150,
        "hrs": 1.5,
        "session_number": 3,
        "merged_lectures": true,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "Lecture",
        "student_count": 150,
        "hrs": 1,
        "session_number": 4,
        "merged_lectures": true,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 2
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 3
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 4
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 2,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 2,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 2
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 2,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 3
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 2,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 4
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 3,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 3,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 2
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 3,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 3
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 3,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 4
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 4,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 1
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 4,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 2
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 4,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 3
    },
    {
        "subj_code": "01.112",
        "subj_name": "Machine Learning",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 4,
        "profId": "MhfSenYDsYh4b6G41hmsk1KKcxF2",
        "class_number": 4
    },
    {
        "subj_code": "b",
        "subj_name": "a",
        "type": "Lecture",
        "student_count": 150,
        "hrs": 1.5,
        "session_number": 1,
        "merged_lectures": true,
        "profId": "test",
        "class_number": 1
    },
    {
        "subj_code": "b",
        "subj_name": "a",
        "type": "Lecture",
        "student_count": 150,
        "hrs": 1,
        "session_number": 2,
        "merged_lectures": true,
        "profId": "test",
        "class_number": 1
    },
    {
        "subj_code": "b",
        "subj_name": "a",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1,
        "session_number": 1,
        "profId": "test",
        "class_number": 1
    },
    {
        "subj_code": "b",
        "subj_name": "a",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1,
        "session_number": 1,
        "profId": "test",
        "class_number": 2
    },
    {
        "subj_code": "b",
        "subj_name": "a",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1,
        "session_number": 1,
        "profId": "test",
        "class_number": 3
    },
    {
        "subj_code": "b",
        "subj_name": "a",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1,
        "session_number": 1,
        "profId": "test",
        "class_number": 4
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 1,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 1
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 1,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 2
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 1,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 3
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 1,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 4
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 2,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 1
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 2,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 2
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 2,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 3
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 2,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 4
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 3,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 1
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 3,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 2
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 3,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 3
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 3,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 4
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 4,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 1
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 4,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 2
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 4,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 3
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "Lecture",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 4,
        "merged_lectures": false,
        "profId": "test",
        "class_number": 4
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "test",
        "class_number": 1
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "test",
        "class_number": 2
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "test",
        "class_number": 3
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 1,
        "profId": "test",
        "class_number": 4
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 2,
        "profId": "test",
        "class_number": 1
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 2,
        "profId": "test",
        "class_number": 2
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 2,
        "profId": "test",
        "class_number": 3
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 2,
        "profId": "test",
        "class_number": 4
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 3,
        "profId": "test",
        "class_number": 1
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 3,
        "profId": "test",
        "class_number": 2
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 3,
        "profId": "test",
        "class_number": 3
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 3,
        "profId": "test",
        "class_number": 4
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 4,
        "profId": "test",
        "class_number": 1
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 38,
        "hrs": 1.5,
        "session_number": 4,
        "profId": "test",
        "class_number": 2
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 4,
        "profId": "test",
        "class_number": 3
    },
    {
        "subj_code": "d",
        "subj_name": "c",
        "type": "CBL",
        "student_count": 37,
        "hrs": 1.5,
        "session_number": 4,
        "profId": "test",
        "class_number": 4
    }
];

export default function () {
  let events = slots.map(slot => {
    return {
      title: slot.subj_name,
      start: new Date(slot.start),
      end: new Date(slot.end),
    }
  });
  return events;
}

/*
function () {
  return [
    {
      id: 0,
      title: 'Software Construction',
      start: new Date(2018, 0, 29, 8, 30, 0),
      end: new Date(2018, 0, 29, 10, 0, 0),
    },
    {
      id: 1,
      title: 'Probability & Statistics',
      start: new Date(2018, 0, 29, 10, 0, 0),
      end: new Date(2018, 0, 29, 11, 30, 0),
    },
    {
      id: 2,
      title: 'Computer System Engineering',
      start: new Date(2018, 0, 29, 11, 30, 0),
      end: new Date(2018, 0, 29, 13, 0, 0),
    },
    {
      id: 3,
      title: 'Computer System Engineering',
      start: new Date(2018, 0, 30, 11, 30, 0),
      end: new Date(2018, 0, 30, 13, 0, 0),
    },
    {
      id: 4,
      title: 'Probability & Statistics',
      start: new Date(2018, 0, 30, 13, 0, 0),
      end: new Date(2018, 0, 30, 14, 30, 0),
    },
    {
      id: 5,
      title: 'Software Construction',
      start: new Date(2018, 0, 30, 14, 30),
      end: new Date(2018, 0, 30, 16, 0),
      desc: 'Big conference for important people',
    },
    {
      id: 6,
      title: 'Meeting',
      start: new Date(2018, 2, 12, 10, 30, 0, 0),
      end: new Date(2018, 2, 12, 12, 30, 0, 0),
      desc: 'Pre-meeting meeting, to prepare for the meeting',
    },
    {
      id: 7,
      title: 'Lunch',
      start: new Date(2018, 2, 12, 12, 0, 0, 0),
      end: new Date(2018, 2, 12, 13, 0, 0, 0),
      desc: 'Power lunch',
    },
    {
      id: 8,
      title: 'Meeting',
      start: new Date(2018, 2, 12, 14, 0, 0, 0),
      end: new Date(2018, 2, 12, 15, 0, 0, 0),
    },
    {
      id: 9,
      title: 'Happy Hour',
      start: new Date(2018, 2, 12, 17, 0, 0, 0),
      end: new Date(2018, 2, 12, 17, 30, 0, 0),
      desc: 'Most important meal of the day',
    },
    {
      id: 10,
      title: 'Dinner',
      start: new Date(2018, 1, 12, 20, 0, 0, 0),
      end: new Date(2018, 1, 12, 21, 0, 0, 0),
    },
    {
      id: 11,
      title: 'Birthday Party',
      start: new Date(2018, 1, 13, 7, 0, 0),
      end: new Date(2015, 1, 13, 10, 30, 0),
    },
    {
      id: 12,
      title: 'Late Night Event',
      start: new Date(2018, 2, 17, 19, 30, 0),
      end: new Date(2018, 2, 18, 2, 0, 0),
    },
    {
      id: 13,
      title: 'Multi-day Event',
      start: new Date(2018, 2, 20, 19, 30, 0),
      end: new Date(2018, 2, 22, 2, 0, 0),
    },
  ];
}
*/